title: "AYOUB-KB"
description: "Liste & writeups - hacking"
theme: jekyll-theme-hacker
author: "Ayoub"

# SITE URL / BASEURL: url = your GitHub user site (no repo name)
url: "https://ayoub-kb.github.io"
baseurl: "/AYOUB-KB"   # leave this if your site is https://ayoub-kb.github.io/AYOUB-KB

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  writeupslist:
    output: true
  ctf:
    output: true
  microcorruption:
    output: true
  247ctf:
    output: true
  tryhackme:
    output: true
  how2stack:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
