title: Ayoub's Projects
description: Welcome to my GitHub Pages site where I share my learning journey, experiments, and projects in cybersecurity.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
favicon: /my-icon.jpg
