# _config.yml
title: "AYOUB-KB"
description: "Liste & writeups - hacking"
theme: jekyll-theme-hacker
author: "Ayoub"
url: "https://ayoub-kb.github.io/AYOUB-KB/" # remplace USERNAME par ton user GitHub

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  microcorruption:
    output: true
  247ctf:
    output: true
  writeupslist:
    output: true
  ctfwriteups:
    output: true
  tryhackme:
    output: true
  how2stack:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default

