# _config.yml
title: "AYOUB-KB"
description: "Liste & writeups - hacking"
theme: jekyll-theme-hacker
author: "Ayoub"
url: "https://ayoub-kb.github.io"
baseurl: "/AYOUB-KB"


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  microcorruption:
    output: true
  writeupslist:
    output: true
  ctfwriteups:
    output: true
  ctf:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default

